# Generated by Django 3.2.13 on 2022-10-21 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_seria', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('f_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('pinfl', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ON HOLD', 'ON HOLD'), ('ACCEPTED', 'ACCEPTED'), ('IGNORED', 'IGNORED')], max_length=55)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
